-- KJ-P8 B1: least-privilege runtime database roles (ADR-0023 revision 2.5, section 27, sealed at 424f85c283a543ba00a650ecc2ecc3a4346623df).
-- GENERATED by scripts/b1/build-manifest.mjs from infrastructure/database/runtime-role-manifest.json.
-- Do not edit by hand: change the decisions file and regenerate. tests/runtime-roles-catalogue.test.ts
-- fails if this file, the manifest and the live catalogue disagree in either direction.
--
-- No credential appears here. The roles are created without a password; a password is set out of band at
-- cutover by the deployment owner. No object changes owner. No row level security setting is relaxed.

do $$ begin if not exists (select 1 from pg_roles where rolname = 'kj_worker') then create role kj_worker; end if; end $$;
alter role kj_worker with login nosuperuser nocreatedb nocreaterole noreplication nobypassrls noinherit connection limit 40;
do $$ begin if not exists (select 1 from pg_roles where rolname = 'kj_door') then create role kj_door; end if; end $$;
alter role kj_door with login nosuperuser nocreatedb nocreaterole noreplication nobypassrls noinherit connection limit 20;

-- No memberships, in either direction.
do $$ declare r record; begin
  for r in select m.roleid::regrole as granted, m.member::regrole as member from pg_auth_members m
    where m.member::regrole::text in ('kj_worker', 'kj_door') or m.roleid::regrole::text in ('kj_worker', 'kj_door') loop
    execute format('revoke %s from %s', r.granted, r.member);
  end loop;
end $$;

-- PUBLIC cleanup: a runtime role must hold nothing through PUBLIC.
revoke create on schema public from public;
revoke execute on all functions in schema public, kernel_private from public;
do $$ begin execute format('revoke temporary on database %I from public', current_database()); end $$;

-- Start from nothing, so that re-applying after a manifest change removes what the manifest no longer lists.
revoke all on all tables in schema public, kernel_private from kj_worker, kj_door;
revoke all on all sequences in schema public, kernel_private from kj_worker, kj_door;
revoke all on all functions in schema public, kernel_private from kj_worker, kj_door;
revoke all on schema public, kernel_private from kj_worker, kj_door;
do $$ declare p record; begin
  for p in select schemaname, tablename, policyname from pg_policies where policyname ~ '^kj_(worker|door)_' loop
    execute format('drop policy %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end $$;

-- kj_worker
do $$ begin execute format('grant connect on database %I to kj_worker', current_database()); end $$;
grant usage on schema kernel_private to kj_worker;
grant usage on schema public to kj_worker;
grant insert on kernel_private.alert_state to kj_worker;
create policy kj_worker_insert on kernel_private.alert_state for insert to kj_worker with check (true);
grant select on kernel_private.alert_state to kj_worker;
create policy kj_worker_select on kernel_private.alert_state for select to kj_worker using (true);
grant update (current_state, first_seen_at, last_notified_at, last_seen_at, occurrence_count, recovered_at, severity) on kernel_private.alert_state to kj_worker;
create policy kj_worker_update on kernel_private.alert_state for update to kj_worker using (true) with check (true);
grant delete on kernel_private.control_assertions to kj_worker;
create policy kj_worker_delete on kernel_private.control_assertions for delete to kj_worker using (true);
grant insert on kernel_private.control_assertions to kj_worker;
create policy kj_worker_insert on kernel_private.control_assertions for insert to kj_worker with check (true);
grant select on kernel_private.control_assertions to kj_worker;
create policy kj_worker_select on kernel_private.control_assertions for select to kj_worker using (true);
grant insert on kernel_private.effect_receipts to kj_worker;
create policy kj_worker_insert on kernel_private.effect_receipts for insert to kj_worker with check (true);
grant select on kernel_private.effect_receipts to kj_worker;
create policy kj_worker_select on kernel_private.effect_receipts for select to kj_worker using (true);
grant insert on kernel_private.execution_bindings to kj_worker;
create policy kj_worker_insert on kernel_private.execution_bindings for insert to kj_worker with check (true);
grant select on kernel_private.execution_bindings to kj_worker;
create policy kj_worker_select on kernel_private.execution_bindings for select to kj_worker using (true);
grant select on kernel_private.identity_cognition_contract_v1 to kj_worker;
create policy kj_worker_select on kernel_private.identity_cognition_contract_v1 for select to kj_worker using (true);
grant insert on kernel_private.identity_cognition_latches to kj_worker;
create policy kj_worker_insert on kernel_private.identity_cognition_latches for insert to kj_worker with check (true);
grant select on kernel_private.identity_cognition_latches to kj_worker;
create policy kj_worker_select on kernel_private.identity_cognition_latches for select to kj_worker using (true);
grant select on kernel_private.identity_governance_state to kj_worker;
create policy kj_worker_select on kernel_private.identity_governance_state for select to kj_worker using (true);
grant insert on kernel_private.notification_delivery_events to kj_worker;
create policy kj_worker_insert on kernel_private.notification_delivery_events for insert to kj_worker with check (true);
grant select on kernel_private.notification_delivery_events to kj_worker;
create policy kj_worker_select on kernel_private.notification_delivery_events for select to kj_worker using (true);
grant insert on kernel_private.notification_outbox to kj_worker;
create policy kj_worker_insert on kernel_private.notification_outbox for insert to kj_worker with check (true);
grant select on kernel_private.notification_outbox to kj_worker;
create policy kj_worker_select on kernel_private.notification_outbox for select to kj_worker using (true);
grant update (attempt_count, delivered_at, last_attempt_at, last_error, next_attempt_at, status) on kernel_private.notification_outbox to kj_worker;
create policy kj_worker_update on kernel_private.notification_outbox for update to kj_worker using (true) with check (true);
grant select on kernel_private.release_activations to kj_worker;
create policy kj_worker_select on kernel_private.release_activations for select to kj_worker using (true);
grant select on kernel_private.release_epoch to kj_worker;
create policy kj_worker_select on kernel_private.release_epoch for select to kj_worker using (true);
grant select on kernel_private.task_admissions to kj_worker;
create policy kj_worker_select on kernel_private.task_admissions for select to kj_worker using (true);
grant insert on kernel_private.telegram_approval_cards to kj_worker;
create policy kj_worker_insert on kernel_private.telegram_approval_cards for insert to kj_worker with check (true);
grant select on kernel_private.telegram_approval_cards to kj_worker;
create policy kj_worker_select on kernel_private.telegram_approval_cards for select to kj_worker using (true);
grant update (attempt_count, claimed_at, message_id, resolved_at, sent_at, state) on kernel_private.telegram_approval_cards to kj_worker;
create policy kj_worker_update on kernel_private.telegram_approval_cards for update to kj_worker using (true) with check (true);
grant insert on kernel_private.telegram_approval_handles to kj_worker;
create policy kj_worker_insert on kernel_private.telegram_approval_handles for insert to kj_worker with check (true);
grant select on kernel_private.telegram_approval_handles to kj_worker;
create policy kj_worker_select on kernel_private.telegram_approval_handles for select to kj_worker using (true);
grant insert on kernel_private.telegram_callback_inbox to kj_worker;
create policy kj_worker_insert on kernel_private.telegram_callback_inbox for insert to kj_worker with check (true);
grant select on kernel_private.telegram_callback_inbox to kj_worker;
create policy kj_worker_select on kernel_private.telegram_callback_inbox for select to kj_worker using (true);
grant update (approval_id, completed_at, disposition, pressed, state) on kernel_private.telegram_callback_inbox to kj_worker;
create policy kj_worker_update on kernel_private.telegram_callback_inbox for update to kj_worker using (true) with check (true);
grant insert on kernel_private.telegram_inbox to kj_worker;
create policy kj_worker_insert on kernel_private.telegram_inbox for insert to kj_worker with check (true);
grant select on kernel_private.telegram_inbox to kj_worker;
create policy kj_worker_select on kernel_private.telegram_inbox for select to kj_worker using (true);
grant update (command, completed_at, disposition, mission, reply_notification_id, state, task_id) on kernel_private.telegram_inbox to kj_worker;
create policy kj_worker_update on kernel_private.telegram_inbox for update to kj_worker using (true) with check (true);
grant select on kernel_private.telegram_operator_state to kj_worker;
create policy kj_worker_select on kernel_private.telegram_operator_state for select to kj_worker using (true);
grant update (next_offset, unauthorised_total, updated_at) on kernel_private.telegram_operator_state to kj_worker;
create policy kj_worker_update on kernel_private.telegram_operator_state for update to kj_worker using (true) with check (true);
grant insert on kernel_private.terminal_results to kj_worker;
create policy kj_worker_insert on kernel_private.terminal_results for insert to kj_worker with check (true);
grant select on kernel_private.terminal_results to kj_worker;
create policy kj_worker_select on kernel_private.terminal_results for select to kj_worker using (true);
grant insert on public.approvals to kj_worker;
create policy kj_worker_insert on public.approvals for insert to kj_worker with check (true);
grant select on public.approvals to kj_worker;
create policy kj_worker_select on public.approvals for select to kj_worker using (true);
grant update (evidence_id, resolved_at, status) on public.approvals to kj_worker;
create policy kj_worker_update on public.approvals for update to kj_worker using (true) with check (true);
grant insert on public.capabilities to kj_worker;
create policy kj_worker_insert on public.capabilities for insert to kj_worker with check (true);
grant select on public.capabilities to kj_worker;
create policy kj_worker_select on public.capabilities for select to kj_worker using (true);
grant insert on public.capability_runs to kj_worker;
create policy kj_worker_insert on public.capability_runs for insert to kj_worker with check (true);
grant select on public.capability_runs to kj_worker;
create policy kj_worker_select on public.capability_runs for select to kj_worker using (true);
grant insert on public.capability_versions to kj_worker;
create policy kj_worker_insert on public.capability_versions for insert to kj_worker with check (true);
grant select on public.capability_versions to kj_worker;
create policy kj_worker_select on public.capability_versions for select to kj_worker using (true);
grant update (id) on public.capability_versions to kj_worker;
create policy kj_worker_rowlock on public.capability_versions for update to kj_worker using (true) with check (false);
grant insert on public.evidence to kj_worker;
create policy kj_worker_insert on public.evidence for insert to kj_worker with check (true);
grant select on public.evidence to kj_worker;
create policy kj_worker_select on public.evidence for select to kj_worker using (true);
grant update (id) on public.evidence to kj_worker;
create policy kj_worker_rowlock on public.evidence for update to kj_worker using (true) with check (false);
grant select on public.faculty_current to kj_worker;
grant insert on public.faculty_pins to kj_worker;
create policy kj_worker_insert on public.faculty_pins for insert to kj_worker with check (true);
grant select on public.faculty_pins to kj_worker;
create policy kj_worker_select on public.faculty_pins for select to kj_worker using (true);
grant select on public.faculty_versions to kj_worker;
create policy kj_worker_select on public.faculty_versions for select to kj_worker using (true);
grant insert on public.identity_activations to kj_worker;
create policy kj_worker_insert on public.identity_activations for insert to kj_worker with check (true);
grant select on public.identity_activations to kj_worker;
create policy kj_worker_select on public.identity_activations for select to kj_worker using (true);
grant insert on public.identity_candidates to kj_worker;
create policy kj_worker_insert on public.identity_candidates for insert to kj_worker with check (true);
grant select on public.identity_candidates to kj_worker;
create policy kj_worker_select on public.identity_candidates for select to kj_worker using (true);
grant update (resolved_at, state) on public.identity_candidates to kj_worker;
create policy kj_worker_update on public.identity_candidates for update to kj_worker using (true) with check (true);
grant select on public.identity_current to kj_worker;
grant select on public.identity_head to kj_worker;
grant insert on public.identity_pins to kj_worker;
create policy kj_worker_insert on public.identity_pins for insert to kj_worker with check (true);
grant select on public.identity_pins to kj_worker;
create policy kj_worker_select on public.identity_pins for select to kj_worker using (true);
grant insert on public.identity_profiles to kj_worker;
create policy kj_worker_insert on public.identity_profiles for insert to kj_worker with check (true);
grant select on public.identity_profiles to kj_worker;
create policy kj_worker_select on public.identity_profiles for select to kj_worker using (true);
grant insert on public.identity_versions to kj_worker;
create policy kj_worker_insert on public.identity_versions for insert to kj_worker with check (true);
grant select on public.identity_versions to kj_worker;
create policy kj_worker_select on public.identity_versions for select to kj_worker using (true);
grant insert on public.memory_candidates to kj_worker;
create policy kj_worker_insert on public.memory_candidates for insert to kj_worker with check (true);
grant select on public.memory_candidates to kj_worker;
create policy kj_worker_select on public.memory_candidates for select to kj_worker using (true);
grant update (decided_at, state, state_reason) on public.memory_candidates to kj_worker;
create policy kj_worker_update on public.memory_candidates for update to kj_worker using (true) with check (true);
grant insert on public.memory_context_assemblies to kj_worker;
create policy kj_worker_insert on public.memory_context_assemblies for insert to kj_worker with check (true);
grant select on public.memory_context_assemblies to kj_worker;
create policy kj_worker_select on public.memory_context_assemblies for select to kj_worker using (true);
grant select on public.memory_current to kj_worker;
grant insert on public.memory_promotions to kj_worker;
create policy kj_worker_insert on public.memory_promotions for insert to kj_worker with check (true);
grant select on public.memory_promotions to kj_worker;
create policy kj_worker_select on public.memory_promotions for select to kj_worker using (true);
grant insert on public.memory_relations to kj_worker;
create policy kj_worker_insert on public.memory_relations for insert to kj_worker with check (true);
grant select on public.memory_relations to kj_worker;
create policy kj_worker_select on public.memory_relations for select to kj_worker using (true);
grant insert on public.memory_versions to kj_worker;
create policy kj_worker_insert on public.memory_versions for insert to kj_worker with check (true);
grant select on public.memory_versions to kj_worker;
create policy kj_worker_select on public.memory_versions for select to kj_worker using (true);
grant update (memory_id) on public.memory_versions to kj_worker;
create policy kj_worker_rowlock on public.memory_versions for update to kj_worker using (true) with check (false);
grant insert on public.outcomes to kj_worker;
create policy kj_worker_insert on public.outcomes for insert to kj_worker with check (true);
grant select on public.outcomes to kj_worker;
create policy kj_worker_select on public.outcomes for select to kj_worker using (true);
grant select on public.principals to kj_worker;
create policy kj_worker_select on public.principals for select to kj_worker using (true);
grant update (id) on public.principals to kj_worker;
create policy kj_worker_rowlock on public.principals for update to kj_worker using (true) with check (false);
grant insert on public.schedule_backfill_requests to kj_worker;
create policy kj_worker_insert on public.schedule_backfill_requests for insert to kj_worker with check (true);
grant insert on public.schedule_fires to kj_worker;
create policy kj_worker_insert on public.schedule_fires for insert to kj_worker with check (true);
grant select on public.schedule_fires to kj_worker;
create policy kj_worker_select on public.schedule_fires for select to kj_worker using (true);
grant update (admission_request_id, admitted_at, admitted_child_task_id, state) on public.schedule_fires to kj_worker;
create policy kj_worker_update on public.schedule_fires for update to kj_worker using (true) with check (true);
grant delete on public.schedule_leases to kj_worker;
create policy kj_worker_delete on public.schedule_leases for delete to kj_worker using (true);
grant insert on public.schedule_leases to kj_worker;
create policy kj_worker_insert on public.schedule_leases for insert to kj_worker with check (true);
grant select on public.schedule_leases to kj_worker;
create policy kj_worker_select on public.schedule_leases for select to kj_worker using (true);
grant update (acquired_at, epoch, expires_at, owner) on public.schedule_leases to kj_worker;
create policy kj_worker_update on public.schedule_leases for update to kj_worker using (true) with check (true);
grant insert on public.schedule_observations to kj_worker;
create policy kj_worker_insert on public.schedule_observations for insert to kj_worker with check (true);
grant select on public.schedule_observations to kj_worker;
create policy kj_worker_select on public.schedule_observations for select to kj_worker using (true);
grant insert on public.schedule_specs to kj_worker;
create policy kj_worker_insert on public.schedule_specs for insert to kj_worker with check (true);
grant select on public.schedule_specs to kj_worker;
create policy kj_worker_select on public.schedule_specs for select to kj_worker using (true);
grant insert on public.schedule_state to kj_worker;
create policy kj_worker_insert on public.schedule_state for insert to kj_worker with check (true);
grant select on public.schedule_state to kj_worker;
create policy kj_worker_select on public.schedule_state for select to kj_worker using (true);
grant update (active_version, state, updated_at, updated_by) on public.schedule_state to kj_worker;
create policy kj_worker_update on public.schedule_state for update to kj_worker using (true) with check (true);
grant insert on public.task_events to kj_worker;
create policy kj_worker_insert on public.task_events for insert to kj_worker with check (true);
grant select on public.task_events to kj_worker;
create policy kj_worker_select on public.task_events for select to kj_worker using (true);
grant update (id) on public.task_events to kj_worker;
create policy kj_worker_rowlock on public.task_events for update to kj_worker using (true) with check (false);
grant insert on public.task_steps to kj_worker;
create policy kj_worker_insert on public.task_steps for insert to kj_worker with check (true);
grant select on public.task_steps to kj_worker;
create policy kj_worker_select on public.task_steps for select to kj_worker using (true);
grant update (contract, status) on public.task_steps to kj_worker;
create policy kj_worker_update on public.task_steps for update to kj_worker using (true) with check (true);
grant insert on public.tasks to kj_worker;
create policy kj_worker_insert on public.tasks for insert to kj_worker with check (true);
grant select on public.tasks to kj_worker;
create policy kj_worker_select on public.tasks for select to kj_worker using (true);
grant update (contract, status, updated_at) on public.tasks to kj_worker;
create policy kj_worker_update on public.tasks for update to kj_worker using (true) with check (true);
grant select on public.tenant_memberships to kj_worker;
create policy kj_worker_select on public.tenant_memberships for select to kj_worker using (true);
grant update (id) on public.tenant_memberships to kj_worker;
create policy kj_worker_rowlock on public.tenant_memberships for update to kj_worker using (true) with check (false);
do $$ declare f record; begin for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'kernel_private' and p.proname = 'identity_cognition_source_v1' loop execute format('grant execute on function %s to kj_worker', f.sig); end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'kernel_private' and p.proname = 'identity_core_canonical_v1' loop execute format('grant execute on function %s to kj_worker', f.sig); end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'kernel_private' and p.proname = 'identity_core_digest_v1' loop execute format('grant execute on function %s to kj_worker', f.sig); end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'kernel_private' and p.proname = 'identity_json_string_v1' loop execute format('grant execute on function %s to kj_worker', f.sig); end loop; end $$;

-- kj_door
do $$ begin execute format('grant connect on database %I to kj_door', current_database()); end $$;
grant usage on schema kernel_private to kj_door;
grant usage on schema public to kj_door;
grant insert on kernel_private.control_events to kj_door;
create policy kj_door_insert on kernel_private.control_events for insert to kj_door with check (true);
grant select on kernel_private.control_events to kj_door;
create policy kj_door_select on kernel_private.control_events for select to kj_door using (true);
grant insert on kernel_private.dispatch_events to kj_door;
create policy kj_door_insert on kernel_private.dispatch_events for insert to kj_door with check (true);
grant select on kernel_private.dispatch_events to kj_door;
create policy kj_door_select on kernel_private.dispatch_events for select to kj_door using (true);
grant select on kernel_private.effect_receipts to kj_door;
create policy kj_door_select on kernel_private.effect_receipts for select to kj_door using (true);
grant insert on kernel_private.execution_bindings to kj_door;
create policy kj_door_insert on kernel_private.execution_bindings for insert to kj_door with check (true);
grant select on kernel_private.execution_bindings to kj_door;
create policy kj_door_select on kernel_private.execution_bindings for select to kj_door using (true);
grant select on kernel_private.release_epoch to kj_door;
create policy kj_door_select on kernel_private.release_epoch for select to kj_door using (true);
grant insert on kernel_private.task_admissions to kj_door;
create policy kj_door_insert on kernel_private.task_admissions for insert to kj_door with check (true);
grant select on kernel_private.task_admissions to kj_door;
create policy kj_door_select on kernel_private.task_admissions for select to kj_door using (true);
grant select on kernel_private.terminal_results to kj_door;
create policy kj_door_select on kernel_private.terminal_results for select to kj_door using (true);
grant select on public.approvals to kj_door;
create policy kj_door_select on public.approvals for select to kj_door using (true);
grant select on public.entities to kj_door;
create policy kj_door_select on public.entities for select to kj_door using (true);
grant select on public.evidence to kj_door;
create policy kj_door_select on public.evidence for select to kj_door using (true);
grant select on public.memory_items to kj_door;
create policy kj_door_select on public.memory_items for select to kj_door using (true);
grant select on public.observations to kj_door;
create policy kj_door_select on public.observations for select to kj_door using (true);
grant select on public.outcomes to kj_door;
create policy kj_door_select on public.outcomes for select to kj_door using (true);
grant select on public.principals to kj_door;
create policy kj_door_select on public.principals for select to kj_door using (true);
grant update (id) on public.principals to kj_door;
create policy kj_door_rowlock on public.principals for update to kj_door using (true) with check (false);
grant select on public.relationships to kj_door;
create policy kj_door_select on public.relationships for select to kj_door using (true);
grant select on public.task_events to kj_door;
create policy kj_door_select on public.task_events for select to kj_door using (true);
grant select on public.tasks to kj_door;
create policy kj_door_select on public.tasks for select to kj_door using (true);
grant select on public.tenant_memberships to kj_door;
create policy kj_door_select on public.tenant_memberships for select to kj_door using (true);
grant update (id) on public.tenant_memberships to kj_door;
create policy kj_door_rowlock on public.tenant_memberships for update to kj_door using (true) with check (false);

-- kernel_private.stamp_binding_provenance() (ADR-0023 revision 2.5, section 27.9): the one B1 SECURITY DEFINER exception. It runs with the
-- owner's rights so that no runtime role needs the write its body performs. Its body is not touched: this migration
-- contains no CREATE FUNCTION for it and changes only its security attributes and its EXECUTE ACL.
alter function kernel_private.stamp_binding_provenance() security definer;
alter function kernel_private.stamp_binding_provenance() set search_path = '';
revoke all on function kernel_private.stamp_binding_provenance() from public;
do $$ declare g record; begin
  for g in select distinct pg_get_userbyid(a.grantee) as grantee from pg_proc p, aclexplode(p.proacl) a
    where p.oid = 'kernel_private.stamp_binding_provenance()'::regprocedure and a.grantee <> 0 and a.grantee <> p.proowner loop
    execute format('revoke all on function kernel_private.stamp_binding_provenance() from %I', g.grantee);
  end loop;
end $$;

-- Pre-COMMIT self-check of the exception (ADR-0023 sections 27.9.4 and 27.10.6): refuse to commit unless it is
-- exactly as sealed. The full inventory, including the frozen platform baseline, is asserted by qualification.
do $$ declare f record; n int; begin
  select p.prosecdef, p.proconfig, p.proacl is null as acl_null,
         encode(sha256(convert_to(replace(p.prosrc, E'\r\n', E'\n'), 'UTF8')), 'hex') as digest,
         (select count(*) from aclexplode(p.proacl) a where not (a.grantee = p.proowner and a.grantor = p.proowner
            and a.privilege_type = 'EXECUTE' and not a.is_grantable)) as foreign_acl,
         (select count(*) from aclexplode(p.proacl) a) as acl_items
    into f from pg_proc p where p.oid = 'kernel_private.stamp_binding_provenance()'::regprocedure;
  if not f.prosecdef then raise exception 'B1: kernel_private.stamp_binding_provenance() is not SECURITY DEFINER' using errcode = '23514'; end if;
  if f.proconfig is distinct from array['search_path=""'] then
    raise exception 'B1: proconfig of kernel_private.stamp_binding_provenance() is %, sealed is the one element search_path=""', f.proconfig using errcode = '23514'; end if;
  if f.acl_null or f.acl_items <> 1 or f.foreign_acl <> 0 then
    raise exception 'B1: EXECUTE ACL of kernel_private.stamp_binding_provenance() is not exactly the owner''s' using errcode = '23514'; end if;
  if f.digest <> '468979611a28ca8e2ec7b46f16402e90ae6622a228e186e1acc7ac45186e439b' then
    raise exception 'B1: source digest of kernel_private.stamp_binding_provenance() is %, pinned 468979611a28ca8e2ec7b46f16402e90ae6622a228e186e1acc7ac45186e439b', f.digest using errcode = '23514'; end if;
  select count(*) into n from pg_proc p join pg_namespace s on s.oid = p.pronamespace where p.proname = 'stamp_binding_provenance'
    and not (s.nspname in ('pg_catalog', 'information_schema', 'pg_toast') or s.nspname ~ '^pg_temp_[0-9]+$' or s.nspname ~ '^pg_toast_temp_[0-9]+$');
  if n <> 1 then raise exception 'B1: % functions are named stamp_binding_provenance; exactly one is sealed', n using errcode = '23514'; end if;
  select count(*) into n from pg_proc p join pg_namespace s on s.oid = p.pronamespace where p.prosecdef and s.nspname in ('public', 'kernel_private');
  if n <> 1 then raise exception 'B1: KernelJSON schemas hold % SECURITY DEFINER functions; stage B1 allows exactly one', n using errcode = '23514'; end if;
end $$;

-- Pre-COMMIT self-check: refuse to commit a role that is not exactly as sealed.
do $$ declare bad text; begin
  select string_agg(rolname, ', ') into bad from pg_roles where rolname in ('kj_worker', 'kj_door')
    and (not rolcanlogin or rolsuper or rolcreatedb or rolcreaterole or rolreplication or rolbypassrls or rolinherit);
  if bad is not null then raise exception 'B1: runtime role attributes are not as sealed: %', bad using errcode = '23514'; end if;
  if exists (select 1 from pg_auth_members m where m.member::regrole::text in ('kj_worker', 'kj_door') or m.roleid::regrole::text in ('kj_worker', 'kj_door')) then
    raise exception 'B1: a runtime role has a role membership' using errcode = '23514'; end if;
end $$;
